name: Update PSX Stock Prices

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  update-prices:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install firebase-admin node-fetch@2
      - name: Run update script
        env:
          FIREBASE_SERVICE_ACCOUNT_BASE64: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}
          DATABASE_URL: "https://psx-tracker-a45fe-default-rtdb.firebaseio.com/"
          EOD_API_KEY: ${{ secrets.EOD_API_KEY }}
        run: node update-script.js
